### PR TITLE
Change the default value of `fill-tail` in `Block.of-inline` to `true`

### LINKED ISSUE #47: Change the default value of `fill-tail` in `Block.of-inline` to `true`
TBA

### PR DESCRIPTION
**Pull request by zeptometer**
This closes #47

### CODE REVIEW

**Comment by nyuichi** [comment]
LGTM for the changes.
But can you reopen a pr towards a new branch called dev-2.0.0?
(Which I am going to use for collecting changes for v2.0.0)
This pr should break the existing programs so we should postpone this until the next major version is released.

**Comment by nyuichi** [comment]
BTW it’s conflicting

**Comment by zeptometer** [comment]
Gotcha 👍

**Comment by zeptometer** [comment]
Created new PR #77

**Pull request closed without merging**
